#!/bin/bash

# Slowhttptest source and documentation available at https://www.kali.org/tools/slowhttptest/
# Invocation command was sourced from the same link as above
# (and explanation of flags can be found there)

# These commands were executed in a WSL session (slowhttptest is Linux-based)

sudo apt install slowhttptest

slowhttptest -c 10000 -H -g -o slowhttp -i 10 -r 200 -t GET -u https://127.0.0.1:5000 -x 24 -p 3

# The file generated by this trial can be found via attack/slowhttp.html for data visualization purposes
# The HTML file can be directly downloaded to device and opened in browser